# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        name: build
        caches:
          - node
        script: 
          - npm install
    - step: 
        name: install cf cli
        script:
          - apt-get update
          - apt-get install cf-cli
          - cf — version
    - step: 
        name: deploy
        deployment: staging
        script: 
          - cf login -o lucasdesouza -s development -a https://api.run.pivotal.io -u $PIVOTAL_USERNAME -p $PIVOTAL_PASSWORD
          - cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
          - cf install-plugin blue-green-deploy   -r CF-Community -f
          - pwd
          - ls -alF
          - cf blue-green-deploy srve-api -f manifest.yml