apiVersion: v1
kind: Deployment
metadata:
  name: breath-landing
  labels:
    app: breath-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: breath-landing
  template:
    metadata:
      labels:
        app: breath-landing
    spec:
      containers:
        - name: breath-landing
          image: ghcr.io/LucasCarioca/breath:latest
          ports:
            - containerPort: 80
              name: breath-landing-port
---
apiVersion: v1
kind: Service
metadata:
  name: breath-landing-cluster-ip
spec:
  ports:
    - name: tcp
      port: 80
      targetPort: breath-landing-port