apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: breath
  name: breath-deployment
  labels:
    app: breath
spec:
  replicas: 1
  selector:
    matchLabels:
      app: breath
  template:
    metadata:
      labels:
        app: breath
    spec:
      containers:
        - name: breath
          image: ghcr.io/lucascarioca/breath:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: breath
  name: breath-np-service
spec:
  type: NodePort
  selector:
    app: breath
  ports:
  - name: breath-http
    port: 80
    nodePort: 30001
    targetPort: 80
