apiVersion: apps/v1
kind: Deployment
metadata:
  name: breath-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: web
  template: 
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: lucasfds/breath
          ports:
            - containerPort: 3000