apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.global-static-ip-name: breath-ip
    networking.gke.io/managed-certificates: breath-certificate
spec:
  backend:
    serviceName: breath-nodeport-service
    servicePort: 80

# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: ingress-service
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     kubernetes.io/ingress.global-static-ip-name: breath-ip
#     networking.gke.io/managed-certificates: breath-certificate
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /?(.*)
#             backend: 
#               serviceName: breath-cluster-ip-service
#               servicePort: 3000