apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: breath
  name: breath
  labels:
    app: breath
spec:
  replicas: 1
  selector:
    matchLabels:
      app: breath
  template:
    metadata:
      labels:
        app: breath
    spec:
      containers:
        - name: breath
          image: ghcr.io/lucascarioca/breath:latest
          ports:
            - containerPort: 80
              name: breath-http
