name: docker build
on:
  push:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: LucasCarioca/docker-multi-arch@v0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}