name: CICD
on:
  push:
    branches: 
    - 'master' 
  pull_request:
    branches:
    - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Netlify Deploy
      uses: jsmrcaga/action-netlify-deploy@v1.0.1
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_TO_PROD: true
        build_directory: build
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run release 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: breath-web
        path: build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: breath-landing
        path: landing
