name: CICD
on:
  push:
jobs:
  release:
    if: github.ref == 'refs/heads/main'
    uses: LucasCarioca/workflows/.github/workflows/release-docker.yml@v0.10.1
    with:
      registry: ghcr.io
      image_name: lucascarioca/breath
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
